[2024-11-13T00:52:38.661+0000] {processor.py:153} INFO - Started process (PID=78113) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T00:52:38.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T00:52:38.664+0000] {logging_mixin.py:137} INFO - [2024-11-13T00:52:38.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T00:52:39.698+0000] {logging_mixin.py:137} INFO - [2024-11-13T00:52:39.697+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T00:52:39.698+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T00:52:39.715+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.059 seconds
[2024-11-13T02:30:16.041+0000] {processor.py:153} INFO - Started process (PID=78151) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:30:16.046+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:30:16.049+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:30:16.049+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:30:17.398+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:30:17.396+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:30:17.399+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:30:17.427+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.409 seconds
[2024-11-13T02:30:47.913+0000] {processor.py:153} INFO - Started process (PID=78205) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:30:47.916+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:30:47.916+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:30:47.916+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:30:48.549+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:30:48.548+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:30:48.550+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:30:48.566+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.655 seconds
[2024-11-13T02:31:18.904+0000] {processor.py:153} INFO - Started process (PID=78243) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:31:18.906+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:31:18.907+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:31:18.907+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:31:19.519+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:31:19.518+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:31:19.520+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:31:19.535+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.635 seconds
[2024-11-13T02:31:49.657+0000] {processor.py:153} INFO - Started process (PID=78297) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:31:49.658+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:31:49.659+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:31:49.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:31:50.298+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:31:50.295+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:31:50.299+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:31:50.316+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.663 seconds
[2024-11-13T02:32:20.628+0000] {processor.py:153} INFO - Started process (PID=78344) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:32:20.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:32:20.631+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:32:20.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:32:21.333+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:32:21.330+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:32:21.334+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:32:21.428+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.805 seconds
[2024-11-13T02:32:51.780+0000] {processor.py:153} INFO - Started process (PID=78392) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:32:51.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:32:51.782+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:32:51.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:32:52.410+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:32:52.408+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:32:52.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:32:52.427+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.654 seconds
[2024-11-13T02:33:23.483+0000] {processor.py:153} INFO - Started process (PID=78446) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:33:23.495+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:33:23.497+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:33:23.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:33:24.175+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:33:24.174+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:33:24.176+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:33:24.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.808 seconds
[2024-11-13T02:33:45.157+0000] {processor.py:153} INFO - Started process (PID=78475) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:33:45.158+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:33:45.158+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:33:45.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:33:46.048+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:33:46.047+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 149, in <module>
    conf={"encoded_result": encoded_result},  # Pass the encoded result to DAG 2
NameError: name 'encoded_result' is not defined
[2024-11-13T02:33:46.049+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:33:46.070+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.917 seconds
[2024-11-13T02:34:16.554+0000] {processor.py:153} INFO - Started process (PID=78522) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:16.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:34:16.557+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:34:16.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:17.303+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:34:17.302+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 149, in <module>
    conf={"encoded_result": encoded_result},  # Pass the encoded result to DAG 2
NameError: name 'encoded_result' is not defined
[2024-11-13T02:34:17.303+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:17.316+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.767 seconds
[2024-11-13T02:34:47.370+0000] {processor.py:153} INFO - Started process (PID=78576) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:47.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:34:47.373+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:34:47.373+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:48.304+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:34:48.302+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 149, in <module>
    conf={"encoded_result": encoded_result},  # Pass the encoded result to DAG 2
NameError: name 'encoded_result' is not defined
[2024-11-13T02:34:48.305+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:48.335+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.971 seconds
[2024-11-13T02:34:54.458+0000] {processor.py:153} INFO - Started process (PID=78578) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:54.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:34:54.460+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:34:54.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:54.465+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:34:54.464+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 149
    conf={"encoded_result": encoded_result， },  # Pass the encoded result to DAG 2
                                          ^
SyntaxError: invalid character in identifier
[2024-11-13T02:34:54.466+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:34:54.489+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.034 seconds
[2024-11-13T02:35:24.805+0000] {processor.py:153} INFO - Started process (PID=78631) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:35:24.809+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:35:24.810+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:35:24.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:35:24.826+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:35:24.824+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 149
    conf={"encoded_result": encoded_result， },  # Pass the encoded result to DAG 2
                                          ^
SyntaxError: invalid character in identifier
[2024-11-13T02:35:24.826+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:35:24.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.067 seconds
[2024-11-13T02:35:55.146+0000] {processor.py:153} INFO - Started process (PID=78668) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:35:55.148+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:35:55.149+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:35:55.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:35:55.154+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:35:55.153+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 149
    conf={"encoded_result": encoded_result， },  # Pass the encoded result to DAG 2
                                          ^
SyntaxError: invalid character in identifier
[2024-11-13T02:35:55.155+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:35:55.177+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.036 seconds
[2024-11-13T02:36:25.481+0000] {processor.py:153} INFO - Started process (PID=78712) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:36:25.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:36:25.484+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:36:25.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:36:25.490+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:36:25.489+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 149
    conf={"encoded_result": encoded_result， },  # Pass the encoded result to DAG 2
                                          ^
SyntaxError: invalid character in identifier
[2024-11-13T02:36:25.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:36:25.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.040 seconds
[2024-11-13T02:36:55.733+0000] {processor.py:153} INFO - Started process (PID=78758) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:36:55.734+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:36:55.735+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:36:55.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:36:55.740+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:36:55.739+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 149
    conf={"encoded_result": encoded_result， },  # Pass the encoded result to DAG 2
                                          ^
SyntaxError: invalid character in identifier
[2024-11-13T02:36:55.740+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:36:55.759+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.030 seconds
[2024-11-13T02:37:04.814+0000] {processor.py:153} INFO - Started process (PID=78777) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:37:04.819+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:37:04.820+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:37:04.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:37:05.392+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:37:05.391+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:37:05.393+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:37:05.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.597 seconds
[2024-11-13T02:37:35.616+0000] {processor.py:153} INFO - Started process (PID=78817) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:37:35.618+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:37:35.619+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:37:35.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:37:36.234+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:37:36.232+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:37:36.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:37:36.246+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.633 seconds
[2024-11-13T02:38:06.539+0000] {processor.py:153} INFO - Started process (PID=78871) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:38:06.541+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:38:06.542+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:38:06.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:38:07.032+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:38:07.031+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:38:07.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:38:07.045+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.510 seconds
[2024-11-13T02:38:37.127+0000] {processor.py:153} INFO - Started process (PID=78909) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:38:37.129+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:38:37.130+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:38:37.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:38:37.601+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:38:37.600+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:38:37.602+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:38:37.612+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.490 seconds
[2024-11-13T02:39:08.333+0000] {processor.py:153} INFO - Started process (PID=78963) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:39:08.333+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:39:08.334+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:39:08.334+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:39:08.908+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:39:08.906+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:39:08.908+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:39:08.921+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.591 seconds
[2024-11-13T02:39:39.245+0000] {processor.py:153} INFO - Started process (PID=79010) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:39:39.247+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:39:39.248+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:39:39.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:39:40.096+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:39:40.094+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:39:40.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:39:40.110+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.869 seconds
[2024-11-13T02:40:10.542+0000] {processor.py:153} INFO - Started process (PID=79055) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:40:10.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:40:10.544+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:40:10.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:40:11.081+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:40:11.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:40:11.082+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:40:11.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.556 seconds
[2024-11-13T02:40:41.658+0000] {processor.py:153} INFO - Started process (PID=79093) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:40:41.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:40:41.663+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:40:41.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:40:42.248+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:40:42.247+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:40:42.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:40:42.262+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.607 seconds
[2024-11-13T02:42:06.819+0000] {processor.py:153} INFO - Started process (PID=60) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:42:06.821+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:42:06.822+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:42:06.822+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:42:08.200+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:42:08.197+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:42:08.201+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:42:08.220+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.405 seconds
[2024-11-13T02:42:38.343+0000] {processor.py:153} INFO - Started process (PID=97) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:42:38.344+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:42:38.345+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:42:38.345+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:42:39.229+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:42:39.227+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:42:39.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:42:39.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.908 seconds
[2024-11-13T02:43:09.573+0000] {processor.py:153} INFO - Started process (PID=152) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:43:09.574+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:43:09.575+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:43:09.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:43:10.248+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:43:10.246+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:43:10.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:43:10.266+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.697 seconds
[2024-11-13T02:43:40.666+0000] {processor.py:153} INFO - Started process (PID=197) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:43:40.670+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:43:40.672+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:43:40.672+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:43:41.589+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:43:41.587+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:43:41.590+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:43:41.615+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.966 seconds
[2024-11-13T02:44:11.836+0000] {processor.py:153} INFO - Started process (PID=243) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:44:11.837+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:44:11.838+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:44:11.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:44:12.544+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:44:12.541+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:44:12.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:44:12.562+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.729 seconds
[2024-11-13T02:44:42.910+0000] {processor.py:153} INFO - Started process (PID=297) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:44:42.913+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:44:42.914+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:44:42.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:44:45.388+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:44:45.379+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:44:45.400+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:44:45.479+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 2.574 seconds
[2024-11-13T02:45:16.076+0000] {processor.py:153} INFO - Started process (PID=335) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:45:16.079+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:45:16.080+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:45:16.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:45:16.798+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:45:16.797+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:45:16.798+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:45:16.814+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.742 seconds
[2024-11-13T02:45:47.160+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:45:47.165+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:45:47.166+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:45:47.166+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:45:47.801+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:45:47.799+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:45:47.801+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:45:47.813+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.658 seconds
[2024-11-13T02:46:18.160+0000] {processor.py:153} INFO - Started process (PID=427) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:18.161+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:46:18.162+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:46:18.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:18.856+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:46:18.854+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:46:18.856+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:18.870+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.714 seconds
[2024-11-13T02:46:23.533+0000] {processor.py:153} INFO - Started process (PID=448) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:23.534+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:46:23.535+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:46:23.535+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:24.075+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:46:24.074+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 150, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:46:24.075+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:24.089+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.562 seconds
[2024-11-13T02:46:54.341+0000] {processor.py:153} INFO - Started process (PID=486) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:54.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:46:54.343+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:46:54.343+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:54.892+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:46:54.890+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 150, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:46:54.893+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:46:54.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.573 seconds
[2024-11-13T02:47:06.707+0000] {processor.py:153} INFO - Started process (PID=504) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:06.709+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:47:06.710+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:47:06.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:07.386+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:47:07.385+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 150, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:47:07.387+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:07.399+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.700 seconds
[2024-11-13T02:47:37.685+0000] {processor.py:153} INFO - Started process (PID=558) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:37.687+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:47:37.688+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:47:37.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:38.404+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:47:38.403+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 150, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:47:38.404+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:38.416+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.735 seconds
[2024-11-13T02:47:46.766+0000] {processor.py:153} INFO - Started process (PID=575) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:46.767+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:47:46.768+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:47:46.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:47.309+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:47:47.307+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:47:47.309+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:47:47.321+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.559 seconds
[2024-11-13T02:48:17.596+0000] {processor.py:153} INFO - Started process (PID=613) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:48:17.597+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:48:17.597+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:48:17.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:48:18.133+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:48:18.132+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:48:18.134+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:48:18.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.556 seconds
[2024-11-13T02:48:48.188+0000] {processor.py:153} INFO - Started process (PID=667) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:48:48.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:48:48.191+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:48:48.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:48:48.812+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:48:48.811+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:48:48.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:48:48.826+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.641 seconds
[2024-11-13T02:49:19.054+0000] {processor.py:153} INFO - Started process (PID=705) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:49:19.056+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:49:19.057+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:49:19.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:49:19.775+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:49:19.773+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 151, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:49:19.775+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:49:19.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.743 seconds
[2024-11-13T02:49:44.776+0000] {processor.py:153} INFO - Started process (PID=759) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:49:44.778+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:49:44.781+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:49:44.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:49:46.135+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:49:46.132+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 150, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:49:46.136+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:49:46.165+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.397 seconds
[2024-11-13T02:50:16.847+0000] {processor.py:153} INFO - Started process (PID=797) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:50:16.849+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:50:16.849+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:50:16.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:50:17.495+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:50:17.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 150, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:50:17.495+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:50:17.508+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.665 seconds
[2024-11-13T02:50:47.545+0000] {processor.py:153} INFO - Started process (PID=851) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:50:47.546+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:50:47.547+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:50:47.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:50:48.374+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:50:48.372+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/feature_and_augm_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/feature_and_augm_dag.py", line 150, in <module>
    dag=dag2,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: trigger_model_training_and_evaluation). Invalid arguments were:
**kwargs: {'trigger_dag_id': 'DAG_Model_Training_and_Evaluation'}
[2024-11-13T02:50:48.375+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:50:48.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.850 seconds
[2024-11-13T02:51:06.665+0000] {processor.py:153} INFO - Started process (PID=873) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:51:06.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:51:06.667+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:51:06.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:51:07.305+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:51:07.345+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:51:07.345+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:51:07.361+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:51:07.361+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:51:07.377+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.716 seconds
[2024-11-13T02:51:37.786+0000] {processor.py:153} INFO - Started process (PID=930) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:51:37.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:51:37.788+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:51:37.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:51:38.345+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:51:38.364+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:51:38.364+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:51:38.383+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:51:38.383+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:51:38.395+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.613 seconds
[2024-11-13T02:52:33.379+0000] {processor.py:153} INFO - Started process (PID=59) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:52:33.382+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:52:33.384+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:52:33.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:52:34.409+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:52:34.512+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:52:34.512+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:52:34.552+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:52:34.552+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:52:34.579+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.205 seconds
[2024-11-13T02:53:05.056+0000] {processor.py:153} INFO - Started process (PID=106) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:53:05.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:53:05.113+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:53:05.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:53:10.173+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:53:10.223+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:53:10.222+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:53:10.260+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:53:10.260+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:53:10.290+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 5.310 seconds
[2024-11-13T02:53:40.775+0000] {processor.py:153} INFO - Started process (PID=151) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:53:40.780+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:53:40.785+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:53:40.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:53:41.965+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:53:42.001+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:53:42.000+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:53:42.057+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.288 seconds
[2024-11-13T02:54:12.745+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:54:12.748+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:54:12.748+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:54:12.748+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:54:13.612+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:54:13.636+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:54:13.635+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:54:13.658+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:54:13.658+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:54:13.681+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.940 seconds
[2024-11-13T02:54:43.889+0000] {processor.py:153} INFO - Started process (PID=243) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:54:43.893+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:54:43.893+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:54:43.893+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:54:44.616+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:54:44.633+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:54:44.633+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:54:44.651+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:54:44.651+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:54:44.663+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.777 seconds
[2024-11-13T02:55:15.054+0000] {processor.py:153} INFO - Started process (PID=281) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:55:15.056+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:55:15.057+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:55:15.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:55:16.000+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:55:16.029+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:55:16.028+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:55:16.056+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:55:16.056+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:55:16.075+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.024 seconds
[2024-11-13T02:55:46.452+0000] {processor.py:153} INFO - Started process (PID=335) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:55:46.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:55:46.455+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:55:46.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:55:47.133+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:55:47.149+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:55:47.149+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:55:47.170+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:55:47.170+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:55:47.182+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.734 seconds
[2024-11-13T02:56:17.509+0000] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:56:17.510+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:56:17.510+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:56:17.510+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:56:18.036+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:56:18.056+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:56:18.056+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:56:18.075+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:56:18.075+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:56:18.086+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.580 seconds
[2024-11-13T02:57:00.463+0000] {processor.py:153} INFO - Started process (PID=62) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:57:00.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:57:00.466+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:57:00.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:57:01.343+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:57:01.399+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:57:01.398+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:57:01.423+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:57:01.423+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:57:01.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.987 seconds
[2024-11-13T02:57:31.575+0000] {processor.py:153} INFO - Started process (PID=100) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:57:31.577+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:57:31.577+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:57:31.577+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:57:32.124+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:57:32.139+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:57:32.139+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:57:32.156+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:57:32.156+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:57:32.167+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.595 seconds
[2024-11-13T02:58:02.901+0000] {processor.py:153} INFO - Started process (PID=154) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:58:02.903+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:58:02.904+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:58:02.904+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:58:03.383+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:58:03.397+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:58:03.397+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:58:03.412+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:58:03.412+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:58:03.423+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.526 seconds
[2024-11-13T02:58:34.161+0000] {processor.py:153} INFO - Started process (PID=199) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:58:34.166+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:58:34.167+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:58:34.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:58:34.957+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:58:34.980+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:58:34.979+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:58:35.014+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:58:35.014+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:58:35.031+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.873 seconds
[2024-11-13T02:59:05.219+0000] {processor.py:153} INFO - Started process (PID=246) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:59:05.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:59:05.220+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:59:05.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:59:05.715+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:59:05.731+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:59:05.731+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:59:05.747+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:59:05.747+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:59:05.757+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.541 seconds
[2024-11-13T02:59:36.515+0000] {processor.py:153} INFO - Started process (PID=300) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:59:36.516+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T02:59:36.517+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:59:36.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:59:36.983+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T02:59:36.996+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:59:36.996+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T02:59:37.012+0000] {logging_mixin.py:137} INFO - [2024-11-13T02:59:37.011+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T02:59:37.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.510 seconds
[2024-11-13T03:00:07.818+0000] {processor.py:153} INFO - Started process (PID=338) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:00:07.821+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:00:07.822+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:00:07.822+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:00:08.435+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:00:08.450+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:00:08.450+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:00:08.469+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:00:08.469+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:00:08.483+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.670 seconds
[2024-11-13T03:00:38.994+0000] {processor.py:153} INFO - Started process (PID=392) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:00:38.995+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:00:38.996+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:00:38.996+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:00:39.521+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:00:39.536+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:00:39.535+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:00:39.552+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:00:39.552+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:00:39.563+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.571 seconds
[2024-11-13T03:01:10.517+0000] {processor.py:153} INFO - Started process (PID=446) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:01:10.518+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:01:10.519+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:01:10.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:01:11.114+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:01:11.134+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:01:11.134+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:01:11.155+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:01:11.155+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:01:11.173+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.661 seconds
[2024-11-13T03:01:42.229+0000] {processor.py:153} INFO - Started process (PID=483) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:01:42.231+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:01:42.232+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:01:42.232+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:01:43.008+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:01:43.034+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:01:43.034+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:01:43.059+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:01:43.058+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:01:43.074+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.849 seconds
[2024-11-13T03:02:14.701+0000] {processor.py:153} INFO - Started process (PID=537) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:02:14.704+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:02:14.706+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:02:14.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:02:15.627+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:02:15.674+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:02:15.673+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:02:15.720+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:02:15.720+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:02:15.750+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.054 seconds
[2024-11-13T03:02:45.933+0000] {processor.py:153} INFO - Started process (PID=575) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:02:45.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:02:45.935+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:02:45.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:02:46.412+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:02:46.427+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:02:46.426+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:02:46.443+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:02:46.442+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:02:46.454+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.524 seconds
[2024-11-13T03:03:17.368+0000] {processor.py:153} INFO - Started process (PID=629) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:03:17.371+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:03:17.372+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:03:17.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:03:18.293+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:03:18.323+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:03:18.323+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:03:18.362+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:03:18.361+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:03:18.393+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.031 seconds
[2024-11-13T03:03:48.504+0000] {processor.py:153} INFO - Started process (PID=667) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:03:48.505+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:03:48.506+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:03:48.505+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:03:48.985+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:03:48.999+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:03:48.998+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:03:49.015+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:03:49.014+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:03:49.026+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.524 seconds
[2024-11-13T03:04:19.498+0000] {processor.py:153} INFO - Started process (PID=721) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:04:19.501+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:04:19.502+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:04:19.502+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:04:19.969+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:04:19.984+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:04:19.984+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:04:20.000+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:04:20.000+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:04:20.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.519 seconds
[2024-11-13T03:04:50.791+0000] {processor.py:153} INFO - Started process (PID=759) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:04:50.792+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:04:50.793+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:04:50.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:04:51.325+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:04:51.344+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:04:51.344+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:04:51.361+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:04:51.361+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:04:51.374+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.586 seconds
[2024-11-13T03:05:21.930+0000] {processor.py:153} INFO - Started process (PID=813) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:05:21.930+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:05:21.931+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:05:21.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:05:22.434+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:05:22.453+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:05:22.453+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:05:22.476+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:05:22.476+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:05:22.496+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.569 seconds
[2024-11-13T03:05:53.426+0000] {processor.py:153} INFO - Started process (PID=867) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:05:53.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:05:53.428+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:05:53.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:05:54.123+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:05:54.142+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:05:54.142+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:05:54.161+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:05:54.161+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:05:54.177+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.757 seconds
[2024-11-13T03:06:24.403+0000] {processor.py:153} INFO - Started process (PID=905) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:06:24.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:06:24.405+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:06:24.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:06:24.892+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:06:24.907+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:06:24.907+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:06:24.928+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:06:24.927+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:06:24.941+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.542 seconds
[2024-11-13T03:06:55.159+0000] {processor.py:153} INFO - Started process (PID=959) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:06:55.160+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:06:55.161+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:06:55.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:06:55.647+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:06:55.660+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:06:55.660+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:06:55.676+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:06:55.676+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:06:55.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.530 seconds
[2024-11-13T03:07:26.287+0000] {processor.py:153} INFO - Started process (PID=997) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:07:26.288+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:07:26.289+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:07:26.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:07:26.772+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:07:26.785+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:07:26.785+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:07:26.801+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:07:26.801+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:07:26.811+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.527 seconds
[2024-11-13T03:07:57.043+0000] {processor.py:153} INFO - Started process (PID=1051) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:07:57.045+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:07:57.046+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:07:57.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:07:57.552+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:07:57.568+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:07:57.567+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:07:57.584+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:07:57.584+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:07:57.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.556 seconds
[2024-11-13T03:08:56.301+0000] {processor.py:153} INFO - Started process (PID=62) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:08:56.303+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:08:56.304+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:08:56.304+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:08:57.095+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:08:57.149+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:08:57.148+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:08:57.171+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:08:57.171+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:08:57.198+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.901 seconds
[2024-11-13T03:09:27.452+0000] {processor.py:153} INFO - Started process (PID=100) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:09:27.453+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:09:27.453+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:09:27.453+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:09:28.032+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:09:28.050+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:09:28.050+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:09:28.069+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:09:28.069+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:09:28.082+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.633 seconds
[2024-11-13T03:09:58.556+0000] {processor.py:153} INFO - Started process (PID=154) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:09:58.557+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:09:58.557+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:09:58.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:09:59.027+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:09:59.042+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:09:59.042+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:09:59.058+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:09:59.058+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:09:59.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.516 seconds
[2024-11-13T03:10:29.712+0000] {processor.py:153} INFO - Started process (PID=201) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:10:29.714+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:10:29.714+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:10:29.714+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:10:30.287+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:10:30.302+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:10:30.302+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:10:30.318+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:10:30.318+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:10:30.329+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.619 seconds
[2024-11-13T03:11:00.829+0000] {processor.py:153} INFO - Started process (PID=246) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:11:00.830+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:11:00.830+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:11:00.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:11:01.304+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:11:01.324+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:11:01.323+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:11:01.347+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:11:01.346+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:11:01.360+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.535 seconds
[2024-11-13T03:11:31.920+0000] {processor.py:153} INFO - Started process (PID=300) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:11:31.921+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:11:31.922+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:11:31.921+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:11:32.394+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:11:32.407+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:11:32.407+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:11:32.422+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:11:32.422+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:11:32.433+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.517 seconds
[2024-11-13T03:12:03.014+0000] {processor.py:153} INFO - Started process (PID=338) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:12:03.016+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:12:03.016+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:12:03.016+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:12:03.482+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:12:03.500+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:12:03.500+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:12:03.518+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:12:03.517+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:12:03.529+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.518 seconds
[2024-11-13T03:12:34.206+0000] {processor.py:153} INFO - Started process (PID=392) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:12:34.208+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:12:34.209+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:12:34.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:12:34.685+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:12:34.700+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:12:34.700+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:12:34.716+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:12:34.716+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:12:34.727+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.523 seconds
[2024-11-13T03:13:05.389+0000] {processor.py:153} INFO - Started process (PID=446) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:13:05.390+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:13:05.393+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:13:05.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:13:05.877+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:13:05.890+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:13:05.890+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:13:05.905+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:13:05.905+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:13:05.916+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.530 seconds
[2024-11-13T03:13:36.001+0000] {processor.py:153} INFO - Started process (PID=483) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:13:36.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:13:36.002+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:13:36.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:13:36.488+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:13:36.502+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:13:36.502+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:13:36.518+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:13:36.518+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:13:36.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.530 seconds
[2024-11-13T03:14:22.972+0000] {processor.py:153} INFO - Started process (PID=60) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:14:22.973+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:14:22.974+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:14:22.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:14:24.119+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:14:24.180+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:14:24.179+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:14:24.205+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:14:24.205+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:14:24.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.259 seconds
[2024-11-13T03:14:54.697+0000] {processor.py:153} INFO - Started process (PID=98) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:14:54.698+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:14:54.699+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:14:54.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:14:55.202+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:14:55.217+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:14:55.216+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:14:55.234+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:14:55.234+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:14:55.245+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.550 seconds
[2024-11-13T03:15:26.619+0000] {processor.py:153} INFO - Started process (PID=152) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:15:26.621+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:15:26.622+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:15:26.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:15:27.112+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:15:27.126+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:15:27.126+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:15:27.142+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:15:27.142+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:15:27.152+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.537 seconds
[2024-11-13T03:15:58.148+0000] {processor.py:153} INFO - Started process (PID=199) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:15:58.149+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:15:58.151+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:15:58.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:15:58.859+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:15:58.876+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:15:58.875+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:15:58.896+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:15:58.896+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:15:58.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.767 seconds
[2024-11-13T03:16:28.982+0000] {processor.py:153} INFO - Started process (PID=244) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:16:28.983+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:16:28.985+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:16:28.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:16:29.489+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:16:29.502+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:16:29.502+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:16:29.517+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:16:29.517+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:16:29.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.549 seconds
[2024-11-13T03:17:00.402+0000] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:17:00.403+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:17:00.404+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:17:00.404+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:17:00.871+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:17:00.884+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:17:00.884+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:17:00.899+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:17:00.899+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:17:00.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.511 seconds
[2024-11-13T03:17:31.662+0000] {processor.py:153} INFO - Started process (PID=335) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:17:31.663+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:17:31.664+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:17:31.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:17:32.128+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:17:32.141+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:17:32.141+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:17:32.157+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:17:32.157+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:17:32.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.511 seconds
[2024-11-13T03:18:02.781+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:18:02.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:18:02.782+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:18:02.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:18:03.278+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:18:03.291+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:18:03.291+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:18:03.307+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:18:03.307+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:18:03.318+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.540 seconds
[2024-11-13T03:18:34.593+0000] {processor.py:153} INFO - Started process (PID=436) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:18:34.595+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:18:34.600+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:18:34.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:18:35.559+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:18:35.584+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:18:35.583+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:18:35.611+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:18:35.611+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:18:35.628+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.042 seconds
[2024-11-13T03:19:06.567+0000] {processor.py:153} INFO - Started process (PID=482) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:19:06.569+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:19:06.569+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:19:06.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:19:07.043+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:19:07.057+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:19:07.057+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:19:07.073+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:19:07.073+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:19:07.084+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.522 seconds
[2024-11-13T03:19:41.573+0000] {processor.py:153} INFO - Started process (PID=536) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:19:41.580+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:19:41.583+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:19:41.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:19:42.655+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:19:42.670+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:19:42.669+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:19:42.687+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:19:42.687+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:19:42.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.139 seconds
[2024-11-13T03:20:12.760+0000] {processor.py:153} INFO - Started process (PID=574) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:20:12.761+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:20:12.761+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:20:12.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:20:13.292+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:20:13.308+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:20:13.307+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:20:13.324+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:20:13.324+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:20:13.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 0.586 seconds
[2024-11-13T03:20:43.538+0000] {processor.py:153} INFO - Started process (PID=628) to work on /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:20:43.540+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/feature_and_augm_dag.py for tasks to queue
[2024-11-13T03:20:43.541+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:20:43.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:20:44.599+0000] {processor.py:753} INFO - DAG(s) dict_keys(['DAG_feature_select_and_data_augmentation']) retrieved from /opt/airflow/dags/feature_and_augm_dag.py
[2024-11-13T03:20:44.632+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:20:44.632+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-11-13T03:20:44.670+0000] {logging_mixin.py:137} INFO - [2024-11-13T03:20:44.669+0000] {dag.py:3441} INFO - Setting next_dagrun for DAG_feature_select_and_data_augmentation to None, run_after=None
[2024-11-13T03:20:44.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/feature_and_augm_dag.py took 1.155 seconds
